version: "3.3"
services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - /data/smart_home_config/nginx_app.conf:/etc/nginx/conf.d/app.conf
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
      - /data/smart_home_config/smarthome_entryform:/var/www/smarthome/entryform
      - /data/smart_home_config/nginx:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 8h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
      - /data/certbot/log:/var/log
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 24h & wait $${!}; done;'"
  prometheus:
    image: prom/prometheus:v2.31.1
    user: "65534:1001"
    ports:
      - "8088:9090"
    environment:
      - "TZ=Europe/Warsaw"
    volumes:
      - "/data/smart_home_config/prometheus.yaml:/etc/prometheus/prometheus.yml"
      - "prometheus_data:/prometheus"
    restart: always
  grafana:
    image: grafana/grafana-oss:8.2.5
    user: "472:1001"
    ports:
      - "3000:3000"
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "/data/smart_home_config/grafana.ini:/etc/grafana/grafana.ini"
      - "/data/smart_home_config/grafana_source.yaml:/etc/grafana/provisioning/datasources/primary.yaml"
      - "/data/smart_home_config/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml"
#      - "/data/smart_home_config/dashboards/spring-boot-statistics_rev2.json:/smart_home/dashboards/spring-boot-statistics_rev2.json"
#      - "/data/smart_home_config/dashboards/smart-home.json:/smart_home/dashboards/smart-home.json"
      - "grafana_dashboards:/grafana_dashboards"
    restart: always
  mysql:
    image: mysql:8.0.27
    user: "0:1001"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
      - "TZ=Europe/Warsaw"
    env_file:
      - "/data/secrets/mysql.env"
    volumes:
      - "mysql_data:/var/lib/mysql"
  rs485-to-grpc:
    image: pejs77/grpc-modbus-adapter:1.0.67
    ports:
      - "8081:8080"
      - "9090:9090"
#      - "5005:5005"
#      - "6001:6001"
    environment:
      - "SPRING_PROFILES_ACTIVE=home"
      - "TZ=Europe/Warsaw"
 #     - "_JAVA_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    volumes:
      - "/data/smart_home_config/grpc_modbus_application-home.yaml:/BOOT-INF/classes/application-home.yaml"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 90s
      timeout: 10s
      retries: 5
  smart-home:
    image: pejs77/smart-home:1.0.16
    ports:
      - "8082:8080"
 #     - "5005:5005"
    environment:
      - "SPRING_PROFILES_ACTIVE=home,local"
#      - "_JAVA_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      - "TZ=Europe/Warsaw"
    volumes:
      - "/data/smart_home_config/smart_home_application-home.yaml:/BOOT-INF/classes/application-home.yaml"
      - "/data/secrets/application-local.properties:/BOOT-INF/classes/application-local.properties"
    depends_on:
      - "rs485-to-grpc"
      - "mysql"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 90s
      timeout: 10s
      retries: 5
volumes:
  mysql_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/var/mysql
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/var/prometheus
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/var/grafana
  grafana_dashboards:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/smart_home_config/dashboards
        
