version: "3.3"
services:
  prometheus:
    image: prom/prometheus:v2.31.1
    user: "65534:1001"
    ports:
      - "8088:9090"
    volumes:
      - "/data/smart_home_config/prometheus.yaml:/etc/prometheus/prometheus.yml"
      - "prometheus_data:/prometheus"
    restart: always
  mysql:
    image: mysql:8.0.27
    user: "0:1001"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    env_file:
      - "/data/secrets/mysql.env"
    volumes:
      - "mysql_data:/var/lib/mysql"
  rs485-to-grpc:
    image: pejs77/grpc-modbus-adapter:1.0.46
    ports:
      - "8081:8080"
      - "9090:9090"
      - "5005:5005"
      - "6001:6001"
    environment:
      - "SPRING_PROFILES_ACTIVE=home"
    volumes:
      - "/data/smart_home_config/grpc_modbus_application-home.yaml:/BOOT-INF/classes/application-home.yaml"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 90s
      timeout: 10s
      retries: 5
  smart-home:
    image: pejs77/smart-home:1.0.6
    ports:
      - "8082:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=home"
    volumes:
      - "/data/smart_home_config/smart_home_application-home.yaml:/BOOT-INF/classes/application-home.yaml"
    depends_on:
      - "rs485-to-grpc"
      - "mysql"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 90s
      timeout: 10s
      retries: 5
volumes:
  mysql_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/var/mysql
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/var/prometheus
