logging:
  level:
    com.gcs: INFO
    com.gcs.gRPCModbusAdapter.functions: WARN
ports:
  entries:
    - name: /dev/ttyUSB0
      baudRate: 9600
      dataBits: 8
      parity: NONE
      stopBits: STOPBITS_1
devices:
  entries:
    - name: ProductionMeter
      id: 1
      serialPort: /dev/ttyUSB0
      deviceFunctions: [TOTAL_POWER, EXPORT_POWER, IMPORT_POWER, CURRENT_POWER, CURRENT_VOLTAGE_PHASE1, CURRENT_VOLTAGE_PHASE2, CURRENT_VOLTAGE_PHASE3]
    - name: MainMeter
      id: 2
      serialPort: /dev/ttyUSB0
      deviceFunctions: [TOTAL_POWER, EXPORT_POWER, IMPORT_POWER, CURRENT_POWER]
