global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "grpc_adapter"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["rs485-to-grpc:8080"]
        labels:
          application: rs485adapter
  - job_name: "smart_home"
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ["smart-home:8080"]
        labels:
          application: "smarthome"
  - job_name: "grafana"
    metrics_path: /grafana/metrics
    static_configs:
       - targets: ["grafana:3000"]
         labels:
           application: "grafana"


# Alertmanager configuration
#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets:
#           - alertmanager:9093

