global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "grpc_adapter"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["rs485-to-grpc:8080"]


# Alertmanager configuration
#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets:
#           - alertmanager:9093

