logging:
  level:
    com.gcs: INFO
grpc:
  client:
    modbusServiceAdapter:
      address: "static://rs485-to-grpc:9090"
      negotiationType: PLAINTEXT

monitoring:
  electricityDevices:
    - deviceName: ProductionMeter
      functions:
        - functionName: "CURRENT_POWER"
          readInterval: 10
          alias: "Instant Production"
          readingType: com.gcs.smarthome.logic.ElectricReading.InstantProductionPower
        - functionName: EXPORT_POWER
          readInterval: 300
          alias: "Energy Production"
          readingType: com.gcs.smarthome.logic.ElectricReading.ProducedPower
        - functionName: CURRENT_VOLTAGE_PHASE1
          readInterval: 60
          alias: "Voltage_Phase_1"
          readingType: com.gcs.smarthome.logic.ElectricReading.CurrentVoltage
        - functionName: CURRENT_VOLTAGE_PHASE2
          readInterval: 60
          alias: "Voltage_Phase_2"
          readingType: com.gcs.smarthome.logic.ElectricReading.CurrentVoltage
        - functionName: CURRENT_VOLTAGE_PHASE3
          readInterval: 60
          alias: "Voltage_Phase_3"
          readingType: com.gcs.smarthome.logic.ElectricReading.CurrentVoltage        
    - deviceName: MainMeter
      functions:
        - functionName: CURRENT_POWER
          readInterval: 10
          alias: "Instant Power Balance"
          readingType: com.gcs.smarthome.logic.ElectricReading.InstantTotalPower
        - functionName: IMPORT_POWER
          readInterval: 300
          alias: "Power Import"
          readingType: com.gcs.smarthome.logic.ElectricReading.ImportedPower
        - functionName: EXPORT_POWER
          readInterval: 300
          alias: "Power Export"
          readingType: com.gcs.smarthome.logic.ElectricReading.ExportedPower
