{
 "title": "Daily History View",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "days",
    "query": {
     "query": "label_values(daily_power_import_total, date)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Totals for all recorded days",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (daily_power_import_total ) + sum(daily_energy_production_total) - sum(daily_power_export_total)",
     "legendFormat": "Total consumption"
    },
    { "expr": "sum(daily_power_import_total)", "legendFormat": "Total import" },
    { "expr": "sum(daily_power_export_total)", "legendFormat": "Total export" },
    {
     "expr": "sum(daily_energy_production_total)",
     "legendFormat": "Total production"
    }
   ]
  },
  {
   "title": "5 days with highest consumption",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(4, avg by (date) (daily_power_import_total + daily_energy_production_total - daily_power_export_total)  )) ",
     "legendFormat": "Top consumption {{date}}"
    }
   ]
  },
  {
   "title": "5 days with highest production",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(5, daily_power_export_total) > 0)",
     "legendFormat": "Export {{date}}"
    }
   ]
  },
  {
   "title": "Import vs. Export",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Import vs. Export",
     "type": "barchart",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "expr": "label_replace(max by (date, type) (daily_power_import_total{date=~\"$days\"}), \"type\", \"Import\", \"date\", \"(.*)\")",
       "legendFormat": "{{date}}-{{type}}"
      },
      {
       "expr": "label_replace(max by (date,type) (daily_power_export_total{date=~\"$days\"}), \"type\",\n\"Export\", \"date\", \"(.*)\")",
       "legendFormat": "{{date}}-{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Day  [[days]]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "days",
   "collapsed": true,
   "panels": [
    {
     "title": "Consumption, production, import & export",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "daily_power_import_total{date=\"$days\"} + \n(daily_energy_production_total{date=\"$days\"} - daily_power_export_total{date=\"$days\"})",
       "legendFormat": "Consumption total"
      },
      {
       "expr": "daily_power_import_total{date=\"$days\"}",
       "legendFormat": "Import total"
      },
      {
       "expr": "daily_energy_production_total{date=\"$days\"}",
       "legendFormat": "Production total"
      },
      {
       "expr": "daily_power_export_total{date=\"$days\"}",
       "legendFormat": "Export total"
      }
     ]
    }
   ]
  }
 ]
}