{
 "title": "Smart Home",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "business_day_up",
    "query": {
     "query": "query_result(business_day_up) \n"
    }
   },
   { "name": "aggregation_interval", "label": "Aggregation interval", "query": "5m,15m,30m,60m,2h,6h,12h" }
  ]
 },
 "panels": [
  {
   "title": "Current Energy Balance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instant_power_balance{application=\"smarthome\"}"
    }
   ]
  },
  {
   "title": "Energy Production",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instant_production{application=\"smarthome\"}"
    }
   ]
  },
  {
   "title": "Current Day statistics ${__to:date:YYYY-MM-DD}",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "increase(power_import_total{date=\"${__to:date:YYYY-MM-DD}\"}[${business_day_up}s])",
     "legendFormat": "Energy Import ${__to:date:YYYY-MM-DD}"
    },
    {
     "expr": "increase(power_export_total{date=\"${__to:date:YYYY-MM-DD}\"}[${business_day_up}s])",
     "legendFormat": "Energy export ${__to:date:YYYY-MM-DD}"
    },
    {
     "expr": "increase(energy_production_total{date=\"${__to:date:YYYY-MM-DD}\"}[${business_day_up}s])",
     "legendFormat": "Total Production ${__to:date:YYYY-MM-DD}"
    }
   ]
  },
  {
   "title": "Production Details",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - max(\n  (\n    increase(power_export_total{date=\"${__to:date:YYYY-MM-DD}\"}[${business_day_up}s]) / \n    increase(energy_production_total{date=\"${__to:date:YYYY-MM-DD}\"}[${business_day_up}s])\n  ) or on() vector(0))",
     "legendFormat": "Energy auto-consumption"
    },
    {
     "expr": "1 - max(\n  (\n    increase(power_export_total{date=\"${__to:date:YYYY-MM-DD}\"}[${business_day_up}s]) /\n    increase(power_import_total{date=\"${__to:date:YYYY-MM-DD}\"}[${business_day_up}s])\n  ) or on() vector(0))",
     "legendFormat": "Import vs. export energy"
    }
   ]
  },
  {
   "title": "Import / Export energy ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "increase(power_import_total{date=\"${__to:date:YYYY-MM-DD}\"}[${aggregation_interval}])",
     "legendFormat": "Energy import"
    },
    {
     "expr": "increase(power_export_total{date=\"${__to:date:YYYY-MM-DD}\"}[${aggregation_interval}])",
     "legendFormat": "Energy export"
    }
   ]
  },
  {
   "title": "Current Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "instant_power_balance", "legendFormat": "Current energy balance" },
    { "expr": "instant_production", "legendFormat": "Current energy production" }
   ]
  }
 ]
}