{
 "title": "NAS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))\n       / sum(rate(node_cpu_seconds_total[5m])))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Use",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{application=\"nas\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "avg(node_memory_MemFree_bytes{application=\"nas\"})",
     "legendFormat": "Free Memory"
    },
    {
     "expr": "avg(node_memory_MemAvailable_bytes{application=\"nas\"})",
     "legendFormat": "Available Memory"
    },
    {
     "expr": "avg(node_memory_SwapCached_bytes{application=\"nas\"})",
     "legendFormat": "SWAP in use"
    }
   ]
  },
  {
   "title": "Component Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (chip, sensor) (node_hwmon_temp_celsius{application=\"nas\"})",
     "legendFormat": "{{chip}}-{{sensor}}"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_temperature{application=\"nas\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available Storage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_filesystem_free_bytes{application=\"nas\", device=\"/dev/md0\"})",
     "legendFormat": "Free Size"
    }
   ]
  },
  {
   "title": "Stored Files (in thousans)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_filesystem_files{application=\"nas\", device=\"/dev/md0\"} / 1000)\n"
    }
   ]
  }
 ]
}